"""Added models

Revision ID: d981ad960a8f
Revises: 
Create Date: 2021-07-13 15:47:54.876765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd981ad960a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subjects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student_grades',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('student_id', mysql.INTEGER(), nullable=True),
    sa.Column('subject_id', mysql.INTEGER(), nullable=True),
    sa.Column('value', mysql.DOUBLE(precision=4, scale=2, asdecimal=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_grades')
    op.drop_table('subjects')
    op.drop_table('students')
    # ### end Alembic commands ###
